name: Get and Cache Dependencies
# no need to add "on" here as the main WF will trigger this custom action
description: "Get the dependencies (via npm) and cache them"
runs:
  # this must be "composite"
  # this will tell Github this is a custom composite action
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      # extra setting here in custom actions and use "run" key
      shell: bash