name: Deploy to AWS S3
description: "Deploy a static website via AWS S3"
inputs:
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket.'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
outputs:
  website-url:
    description: 'URL of the deployed website'
    # the "value" needs to set inside the js code, unlike the composite actions
runs:
  using: 'node16'
  # in composite actions, we specify "steps"
  # in js actions, we specify "main" as the file that should be executed
  # here the main file is in the same folder, so no need the whole path
  # the file doesn't have to be "main"
  main: 'main.js'