name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: unbuntu-latest
    steps:
      - name: Output Github context
        # it's called "Expression"
        run: echo "${{ toJSON(github) }}"