name: Label Issues (Permissions Example)
on:
  issues:
    types:
      - opened
# can assign permissions here, which will be applied to all Jobs
# permissions:
jobs:
  assign-label:
    # could assign permissions here, which will be applied job by job
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-type: application/json' \
          -d '{
              "labels": ["bug"]
            }' \
          --fail