name: Events Deep Dive - Demo 1
on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main      # main
      - 'dev-*'   # dev-new, dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
  workflow_dispatch:
  push:
    branches:
      - main      # main
      - 'dev-*'   # dev-new, dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
    paths-ignore:
      # means the push event will be triggered
      # ONLY if at least one file changed ELSEWHERE other than the folders below.
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."