name: Conditional Execution - Matrix Demo
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        # can be any value that could be changing
        # and for which you want to run the job
        # the jobs will run ALL COMBINATIONS of values, so in total 6 jobs run in parallel
        node-version: [12, 14, 16]
        operation-system: [ubuntu-latest, windows-latest]
    # use context expression here
    # to run each operating system and in parallel
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build